### ISSUE TITLE
Spelling mistake?

### ISSUE THREAD

**Issue by web-liuyang** [ServeDynamicUI/serve_dynamic_ui#1]
<img width="639" alt="image" src="https://github.com/Arunshaik2001/serve_dynamic_ui/assets/52391595/3301060a-ce46-43d8-a3f2-33ab35ba2b4f">

In the README.MD

screenn => screens ?

**Comment by Arunshaik2001** [comment]
Hi @web-liuyang thank you for pointing out. updated readme
