### ISSUE TITLE
Build from json string ?

### ISSUE THREAD

**Issue by aktxyz** [ServeDynamicUI/serve_dynamic_ui#39]
Is there a way to build a dynamic widget from some json in a string ? Ie not from file or url ?

**Comment by Arunshaik2001** [comment]
Hi @aktxyz, you can create dynamic widget by using

`WidgetUtil.fromJson`

it requires map so you can decode the string the map using jsonDecode

**Comment by Arunshaik2001** [comment]
Hi @aktxyz , i hope your query is resolved. Closing the issue. Feel free to reopen
